<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DevStatusCenter.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DevStatusCenter.Domain/DevStatusCenter.Domain.csproj" />
  </ItemGroup>
</Project>

